### ISSUE TITLE
cannot add component

### ISSUE THREAD

**Issue by chenull** [redwoodjs/rw-shad#4]
Hi Tobbe, great tool rwgc is. it's been some months back since i use rwgc, and today, i cannot add a component

```
❯ yarn rwgc button
⠇ Adding component(s)...
◼ Formatting source(s)...
◼ Renaming file(s)...
```

it stuck on `Adding component(s)...`

but when i added component manually using npx, it worked:

```
❯ npx shadcn-ui@latest add --cwd web/config --path web/src/components/ui button
✔ Done.
```

thanks

**Comment by Tobbe** [comment]
I've updated rw-shad, hopefully fixing this issue. Please create a new issue if it still isn't working for you
