### ISSUE TITLE
Adding lucide-react automatically

### ISSUE THREAD

**Issue by pantheredeye** [redwoodjs/rw-shad#8]
Is there a way to add lucide-react automatically with the install, or component install, or alert the user that it (or some other library) might be needed? I didn't know that was a dependency in the dropdownmenu item, but i had the code open and saw it had a red squiggle.

It might have still worked, but I might not have ever realized something was missing!

**Comment by Tobbe** [comment]
The setup command should have already added lucide for you. How did you setup rw-shad?

Here's the relevant code from the `setup-rw-shad` package

```ts
await execa.command(
  'yarn workspace web add tailwindcss-animate class-variance-authority clsx tailwind-merge lucide-react',
  process.env['RWJS_CWD']
    ? {
        cwd: process.env['RWJS_CWD'],
      }
    : {}
)
```

**Comment by pantheredeye** [comment]
old package shows it in there ,added with rw-shad. hmm. when i had the file open it had red squiggles for lucide. *shrug* This is a non-issue! Thanks!
